/****** Object:  Table [dbo].[Advertisers]    Script Date: 06-06-2023 16:49:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Advertisers](
	[ADVERTISERID] [int] NOT NULL,
	[ADVERTISERNAME] [nvarchar](max) NOT NULL,
	[AFFILIATENETWORKID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ADVERTISERID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AffiliateNetwork]    Script Date: 06-06-2023 16:49:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AffiliateNetwork](
	[AFFILIATENETWORKID] [int] NOT NULL,
	[AFFILIATENETWORKNAME] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AFFILIATENETWORKID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Clicks]    Script Date: 06-06-2023 16:49:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clicks](
	[CLICKID] [int] NOT NULL,
	[DOMAINNAME] [nvarchar](max) NOT NULL,
	[OFFER_ID] [int] NOT NULL,
	[COUPONFOLLOW_SESSION_ID] [int] NULL,
	[PARTNERWEBSITEID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CLICKID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CouponCodes]    Script Date: 06-06-2023 16:49:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CouponCodes](
	[COUPONCODEID] [int] NOT NULL,
	[DOMAINNAMEID] [int] NOT NULL,
	[COUPON_CODE] [nvarchar](max) NOT NULL,
	[ISEXCLUSIVE] [bit] NOT NULL,
	[EXPIREDATE] [datetime] NOT NULL,
	[CATCLASTSAVINGON] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[COUPONCODEID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DomainNames]    Script Date: 06-06-2023 16:49:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DomainNames](
	[DOMAINNAMEID] [int] NOT NULL,
	[DOMAINNAME] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[DOMAINNAMEID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Orders]    Script Date: 06-06-2023 16:49:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[ORDERID] [int] NOT NULL,
	[CLICKID] [int] NOT NULL,
	[CREATEDON] [datetime] NOT NULL,
	[TRANSACTIONDATE] [datetime] NOT NULL,
	[SALEAMOUNT] [float] NOT NULL,
	[COMMISSIONAMOUNT] [float] NOT NULL,
	[CURRENCY] [nvarchar](max) NOT NULL,
	[AFFILIATENETWORKID] [int] NOT NULL,
	[ADVERTISERID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ORDERID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PageViews]    Script Date: 06-06-2023 16:49:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PageViews](
	[EVENT_ID] [nvarchar](max) NOT NULL,
	[EMAIL_PROFILE_ID] [nvarchar](max) NOT NULL,
	[CAMPAIGN_ID] [nvarchar](max) NOT NULL,
	[DOMAIN_NAME] [nvarchar](max) NOT NULL,
	[USER_SESSION_ID] [nvarchar](max) NOT NULL,
	[PAGE_VIEW_AT_PT] [datetime] NOT NULL,
	[PAGE_TITLE] [nvarchar](max) NOT NULL,
	[CITY] [nvarchar](max) NOT NULL,
	[COUNTRY] [nvarchar](max) NOT NULL,
	[REGION_NAME] [nvarchar](max) NOT NULL,
	[BROWSER_NAME] [nvarchar](max) NOT NULL,
	[OPERATING_SYSTEM_VERSION] [nvarchar](max) NOT NULL,
	[DEVICE_NAME] [nvarchar](max) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PartnerWebsites]    Script Date: 06-06-2023 16:49:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PartnerWebsites](
	[PARTNERWEBSITEID] [int] NOT NULL,
	[NAME] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PARTNERWEBSITEID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Promotions]    Script Date: 06-06-2023 16:49:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Promotions](
	[PROMOTIONID] [int] NOT NULL,
	[DOMAINNAMEID] [int] NOT NULL,
	[EXPIREDATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PROMOTIONID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Advertisers]  WITH CHECK ADD FOREIGN KEY([AFFILIATENETWORKID])
REFERENCES [dbo].[AffiliateNetwork] ([AFFILIATENETWORKID])
GO
ALTER TABLE [dbo].[Clicks]  WITH CHECK ADD FOREIGN KEY([OFFER_ID])
REFERENCES [dbo].[Promotions] ([PROMOTIONID])
GO
ALTER TABLE [dbo].[Clicks]  WITH CHECK ADD FOREIGN KEY([PARTNERWEBSITEID])
REFERENCES [dbo].[PartnerWebsites] ([PARTNERWEBSITEID])
GO
ALTER TABLE [dbo].[CouponCodes]  WITH CHECK ADD FOREIGN KEY([DOMAINNAMEID])
REFERENCES [dbo].[DomainNames] ([DOMAINNAMEID])
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD FOREIGN KEY([ADVERTISERID])
REFERENCES [dbo].[Advertisers] ([ADVERTISERID])
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD FOREIGN KEY([AFFILIATENETWORKID])
REFERENCES [dbo].[AffiliateNetwork] ([AFFILIATENETWORKID])
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD FOREIGN KEY([CLICKID])
REFERENCES [dbo].[Clicks] ([CLICKID])
GO
ALTER TABLE [dbo].[Promotions]  WITH CHECK ADD FOREIGN KEY([DOMAINNAMEID])
REFERENCES [dbo].[DomainNames] ([DOMAINNAMEID])
GO
